services:
  frontend:
    build:
      context: ./Angular-Todo-List
      dockerfile: Dockerfile
    ports:
      - "4200:80"  # Map port 80 in the container to port 4200 on the host

  backend:
    build:
      context: ./tovodoo
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Map port 8080 in the container to port 8080 on the host
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update